# Generated by Django 3.1.7 on 2021-03-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartOtherFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_platter', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_platter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.dinnerplatter')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOtherFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.extra')),
            ],
        ),
        migrations.CreateModel(
            name='OtherFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('other_food_type', models.CharField(choices=[('Pasta', 'Pasta'), ('Salad', 'Salad')], max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('Regular', 'Regular'), ('Sicilian', 'Sicilian')], max_length=64)),
                ('topping', models.CharField(choices=[('Cheese', 'Cheese'), ('1 topping', 'One Topping'), ('2 toppings', 'Two Toppings'), ('3 toppings', 'Three Toppings'), ('Special', 'Special'), ('1 item', 'One Item'), ('2 items', 'Two Items'), ('3 items', 'Three Items')], max_length=64)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.extra')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sub')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='ordersub',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sub'),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pizza'),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.topping'),
        ),
        migrations.AddField(
            model_name='orderotherfood',
            name='other_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.otherfood'),
        ),
        migrations.AddField(
            model_name='cartsub',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.extra'),
        ),
        migrations.AddField(
            model_name='cartsub',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sub'),
        ),
        migrations.AddField(
            model_name='cartpizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pizza'),
        ),
        migrations.AddField(
            model_name='cartpizza',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.topping'),
        ),
        migrations.AddField(
            model_name='cartotherfood',
            name='other_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.otherfood'),
        ),
        migrations.AddField(
            model_name='cartdinnerplatter',
            name='dinner_platter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.dinnerplatter'),
        ),
    ]
