# Generated by Django 3.1.7 on 2021-03-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210316_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('menu', models.CharField(choices=[('Regular Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza'), ('Subs', 'Subs'), ('Pasta', 'Pasta'), ('Salads', 'Salads'), ('Dinner Platters', 'Dinner Platters')], max_length=64)),
                ('topping_type', models.CharField(choices=[('Cheese', 'Cheese'), ('1 topping', 'One'), ('2 toppings', 'Two'), ('3 toppings', 'Three'), ('Special', 'Special')], max_length=64)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_type', models.CharField(choices=[('Ordered', 'Ordered'), ('Cart', 'Cart')], max_length=64)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.topping')),
            ],
        ),
        migrations.CreateModel(
            name='ToppingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_num', models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two')])),
                ('topping_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartotherfood',
            name='other_food',
        ),
        migrations.RemoveField(
            model_name='cartpizza',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='cartpizza',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='cartsub',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='cartsub',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='customercart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderdinnerplatter',
            name='dinner_platter',
        ),
        migrations.RemoveField(
            model_name='orderotherfood',
            name='other_food',
        ),
        migrations.RemoveField(
            model_name='orderpizza',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='orderpizza',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='ordersub',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='ordersub',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='subextra',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='subextra',
            name='sub',
        ),
        migrations.DeleteModel(
            name='CartDinnerPlatter',
        ),
        migrations.DeleteModel(
            name='CartOtherFood',
        ),
        migrations.DeleteModel(
            name='CartPizza',
        ),
        migrations.DeleteModel(
            name='CartSub',
        ),
        migrations.DeleteModel(
            name='CustomerCart',
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.DeleteModel(
            name='OrderDinnerPlatter',
        ),
        migrations.DeleteModel(
            name='OrderOtherFood',
        ),
        migrations.DeleteModel(
            name='OrderPizza',
        ),
        migrations.DeleteModel(
            name='OrderSub',
        ),
        migrations.DeleteModel(
            name='OtherFood',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='SubExtra',
        ),
    ]
